### ISSUE TITLE
Radarplot Marker setting

### ISSUE THREAD

**Issue by Changwen-Wu** [NewGuy012/spider_plot#10]
Hi, spider_plot developers.

Thanks for the useful toolbox. 

I have 13 pearson r value to show, and 7 out of 13 were significant, Would it be possible to set markers for those significant rather than all data?

Thank you!

**Comment by NewGuy012** [comment]
Hello, yes it is possible but it will have to be a workaround as a line plot currently only allow one marker. Do you have some sample data or sample image I could work off of? Let me look into adding an option to plot markers point by point.

[https://www.mathworks.com/matlabcentral/answers/2076901-is-it-possible-to-have-a-line-graph-with-a-different-marker-for-each-point-on-the-same-line](url)

**Comment by NewGuy012** [comment]
I was able to create a workaround by plotting the initial lines with no markers and then plotting the desired markers point by point. Please try this out and let me know if it works for you. Thanks!

```matlab
P = [5 3 9 1 2];
P1 = [P(1) inf inf inf inf];
P3 = [inf inf P(3) inf inf];
P4 = [inf inf inf P(4) inf];

f = figure;
ax = axes;

% Spider plot
spider_plot(P,...
    'AxesLimits', [1, 1, 1, 1, 1; 10, 10, 10, 10, 10],...
    'AxesPrecision', 0,...
    'Marker', 'none',...
    'AxesHandle', ax);
spider_plot(P1,...
    'AxesLimits', [1, 1, 1, 1, 1; 10, 10, 10, 10, 10],...
    'AxesPrecision', 0,...
    'Marker', 'o',...
    'LineStyle', 'none',...
    'Color', 'r',...
    'AxesHandle', ax);
spider_plot(P3,...
    'AxesLimits', [1, 1, 1, 1, 1; 10, 10, 10, 10, 10],...
    'AxesPrecision', 0,...
    'Marker', 'o',...
    'LineStyle', 'none',...
    'Color', 'r',...
    'AxesHandle', ax);
spider_plot(P4,...
    'AxesLimits', [1, 1, 1, 1, 1; 10, 10, 10, 10, 10],...
    'AxesPrecision', 0,...
    'Marker', 'o',...
    'LineStyle', 'none',...
    'Color', 'r',...
    'AxesHandle', ax);
```


![image](https://github.com/user-attachments/assets/3e08b599-48d7-46a3-a766-8b770a61d307)

**Comment by Changwen-Wu** [comment]
Thanks for the code! It really helps :)
