### ISSUE TITLE
Ability to set line transparency?

### ISSUE THREAD

**Issue by anthony-wang** [NewGuy012/spider_plot#2]
Hello! 

I really like these functions you have provided and thank you for putting them online.
I wanted to ask, if there is a way to easily set the line transparency in a similar way to setting the `FillTransparency `?

Thanks!

**Comment by NewGuy012** [comment]
Hi Anthony,

Good question! Let me take a look if that is possible and I will get back to you.

Thanks,

**Comment by NewGuy012** [comment]
Hi Anthony,

I was able to add the feature requested as options for 'LineTransparency' and 'MarkerTransparency'. Please try the latest functions.
You can specify these options either as one scalar value between [0, 1] or as an array of values.

Thanks!

```matlab
%% Example %%
% Initialize data points
D1 = [5 3 9 1 2];
D2 = [5 8 7 2 9];
D3 = [8 2 1 4 6];
P = [D1; D2; D3];

% Spider plot
spider_plot(P,...
    'LineTransparency', [0.1, 0.5, 1],...
    'MarkerTransparency', [0.1, 0.5, 1]);

spider_plot(P,...
    'LineTransparency', 0.5,...
    'MarkerTransparency', 0.5);
```
