### ISSUE TITLE
Showing and changing color of the grid line at 0 of the plotted data

### ISSUE THREAD

**Issue by waqasahmad531** [NewGuy012/spider_plot#5]
Hi, 

Would it be possible to to show the zero level on the plotted grid with different color and thickness? 

For example, in the attached figure, a different color and thickness at zero would make the data more readable. 
![image](https://user-images.githubusercontent.com/36894997/153653808-c5d18a66-1282-4b2a-ac18-aafef0a03793.png)

If it is possible, then we would need to change the grid line accordingly for the plot to look presentable. 

Looking forward to your response.

**Comment by waqasahmad531** [comment]
I checked the source code again, there is an option of AxesColor but that would change the color for all of them. My query is specifically for the case where the value would be 0. Something similar to Cartesian coordinate system where axes lines passing through origin (0,0) are bit darker and thicker.

**Comment by NewGuy012** [comment]
Sure, let me look into this.

**Comment by NewGuy012** [comment]
So did you mean something like this? FYI, I entered in "AxesLimits" and "AxesInterval" options in a way to make the axes tick marks at my desired intervals.

The following code is for the latest version:
```matlab
% Initialize data points
D1 = [5 3 9 1 2 -8];
D2 = [5 8 7 2 9 -2];
D3 = [8 2 1 4 6 -10];
P = [D1; D2; D3];

% Spider plot
spider_plot(P,...
    'AxesDisplay', 'one',...
    'AxesInterval', 4,...
    'AxesLimits', [-10 -10 -10 -10 -10 -10; 10 10 10 10 10 10],...
    'AxesZero', 'on',...
    'AxesZeroWidth', 1.5,...
    'AxesZeroColor', 'k',...
    'AxesHorzAlign', 'right',...
    'AxesPrecision', 0);
```

![sample](https://user-images.githubusercontent.com/22648054/153781216-55d1152d-cbf7-4cf8-a406-0aab78ce359e.png)
