### ISSUE TITLE
AxesHandle Bug

### ISSUE THREAD

**Issue by schkorf1** [NewGuy012/spider_plot#7]
I believe I found a bug with the option AxesHandle. The requested axes is not respected. See below. In general, very nice job on the function and very well documented.

```
D1 = [5 3 9 1 2];
D2 = [5 8 7 2 9];
D3 = [8 2 1 4 6];
P = [D1; D2; D3];

% Create a new figure
figure
% Get the axis handle
h1=gca;

% Create another figure
figure
h2=gca;

% Spider plot
% Based on the option I expect the plot to be in the first figure, but it is plotted to the second figure.
spider_plot_R2019b(P,'AxesHandle',h1);
```

**Comment by NewGuy012** [comment]
Good catch. Will write a fix for this bug shortly.

**Comment by NewGuy012** [comment]
Fixed. Please try again with the latest master branch. Thanks!
